name: 'Write-Good Linter'
description: 'Lints markdown files using write-good'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install write-good
      run: npm install -g write-good
      shell: bash

    - name: Lint Markdown files
      run: find . -name "*.md" -print0 | xargs -0 write-good
      shell: bash
